Many modules are hidden in this stack. Use "module --show_hidden spider SOFTWARE" if you are not able to find the required software

Lmod is automatically replacing "gcc/12.2.0" with
"intel-oneapi-compilers/2023.2.0".


Inactive Modules:
  1) cuda/12.1.1       3) openblas/0.3.24     5) python_cuda/3.11.6
  2) nccl/2.18.3-1     4) python/3.11.6

/cluster/project/cvl/guosun/shangye/Vim/lib/python3.10/site-packages/torch/distributed/launch.py:181: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
/cluster/project/cvl/guosun/shangye/Vim/lib/python3.10/site-packages/torch/nn/modules/conv.py:456: UserWarning: Applied workaround for CuDNN issue, install nvrtc.so (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:80.)
  return F.conv2d(input, weight, bias, self.stride,
/cluster/project/cvl/guosun/shangye/Vim/lib/python3.10/site-packages/torch/nn/modules/conv.py:456: UserWarning: Applied workaround for CuDNN issue, install nvrtc.so (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:80.)
  return F.conv2d(input, weight, bias, self.stride,
/cluster/project/cvl/guosun/shangye/Vim/lib/python3.10/site-packages/torch/nn/modules/conv.py:456: UserWarning: Applied workaround for CuDNN issue, install nvrtc.so (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:80.)
  return F.conv2d(input, weight, bias, self.stride,
/cluster/project/cvl/guosun/shangye/Vim/lib/python3.10/site-packages/torch/nn/modules/conv.py:456: UserWarning: Applied workaround for CuDNN issue, install nvrtc.so (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:80.)
  return F.conv2d(input, weight, bias, self.stride,
/cluster/project/cvl/guosun/shangye/Vim/lib/python3.10/site-packages/torch/nn/modules/conv.py:456: UserWarning: Applied workaround for CuDNN issue, install nvrtc.so (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:80.)
  return F.conv2d(input, weight, bias, self.stride,
/cluster/project/cvl/guosun/shangye/Vim/lib/python3.10/site-packages/torch/nn/modules/conv.py:456: UserWarning: Applied workaround for CuDNN issue, install nvrtc.so (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:80.)
  return F.conv2d(input, weight, bias, self.stride,
/cluster/project/cvl/guosun/shangye/Vim/lib/python3.10/site-packages/torch/nn/modules/conv.py:456: UserWarning: Applied workaround for CuDNN issue, install nvrtc.so (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:80.)
  return F.conv2d(input, weight, bias, self.stride,
/cluster/project/cvl/guosun/shangye/Vim/lib/python3.10/site-packages/torch/nn/modules/conv.py:456: UserWarning: Applied workaround for CuDNN issue, install nvrtc.so (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:80.)
  return F.conv2d(input, weight, bias, self.stride,
Traceback (most recent call last):
  File "/scratch/tmp.14195153.guosun/main.py", line 580, in <module>
    main(args)
  File "/scratch/tmp.14195153.guosun/main.py", line 529, in main
    train_stats = train_one_epoch(
  File "/scratch/tmp.14195153.guosun/engine.py", line 37, in train_one_epoch
    for samples, targets in metric_logger.log_every(data_loader, print_freq, header):
  File "/scratch/tmp.14195153.guosun/utils.py", line 146, in log_every
    print(log_msg.format(
  File "/scratch/tmp.14195153.guosun/utils.py", line 184, in print
    builtin_print(*args, **kwargs)
OSError: [Errno 122] Disk quota exceeded
[2024-11-05 18:06:53,289] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 682653 closing signal SIGTERM
[2024-11-05 18:06:53,290] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 682654 closing signal SIGTERM
[2024-11-05 18:06:53,291] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 682655 closing signal SIGTERM
[2024-11-05 18:06:53,291] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 682656 closing signal SIGTERM
[2024-11-05 18:06:53,291] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 682657 closing signal SIGTERM
[2024-11-05 18:06:53,292] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 682658 closing signal SIGTERM
[2024-11-05 18:06:53,293] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 682659 closing signal SIGTERM
[2024-11-05 18:06:53,759] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 682652) of binary: /cluster/project/cvl/guosun/shangye/Vim/bin/python
Traceback (most recent call last):
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.10.13-f2dq73rq2g6nuqmlbmfpcrfs6fe72i6f/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.10.13-f2dq73rq2g6nuqmlbmfpcrfs6fe72i6f/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/cluster/project/cvl/guosun/shangye/Vim/lib/python3.10/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/cluster/project/cvl/guosun/shangye/Vim/lib/python3.10/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/cluster/project/cvl/guosun/shangye/Vim/lib/python3.10/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/cluster/project/cvl/guosun/shangye/Vim/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/cluster/project/cvl/guosun/shangye/Vim/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/cluster/project/cvl/guosun/shangye/Vim/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
main.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-11-05_18:06:53
  host      : eu-g6-007.euler.ethz.ch
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 682652)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
